require("jamie.set")
require('jamie.packer')
require("jamie.treesitter")
require("jamie.cmp")
require("jamie.lsp")
require("jamie.autopairs")
require("jamie.navic")
require("jamie.copilot")

-- require("jamie.commands")
require("jamie.remap")
require('telescope').setup()
