require('jamie.packer')
require('telescope').setup()
require("jamie.set")
require("jamie.telescope")
require("jamie.vimtex")
require('jamie.tabnine')
require("jamie.treesitter")
require("jamie.bufferline")
require("illuminate")
require("jamie.cmp")
--require("jamie.lspkind")
require("jamie.cbyu")
--require("jamie.lsp")
require("jamie.autopairs")
require("jamie.navic")
require("jamie.copilot")
-- require("jamie.commands")
require("jamie.remap")
vim.opt.termguicolors = true
require("bufferline").setup{}
